### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by volcacius** [jucaleb4/Bilinear-Algorithms-for-Convolution#3]
Hello,

Thanks for the nice work with this repo and your paper. I was wondering if you could add a license to it so that the code can be easily included in other projects.
The repo mentions that the code is freely available for everyone to use but unfortunately without a proper license it becomes complicated to do so in practice. Something permissive like MIT or Apache 2.0 or BSD would be great.

Thanks!

**Comment by jucaleb4** [comment]
Hi @volcacius, thanks for bringing this up (and sorry for getting to this so late). The most recent commit (3f23bed) should resolve this.
